### ISSUE TITLE
Error and Crash

### ISSUE THREAD

**Issue by timothytay** [Xenophilicy/OreGen#2]
Hello, I tried the OreGen plugin today and noticed a very big problem. After adding the plugin successfully, when a player creates a cobblestone generator or causes it to generate a new block, my server crashes followed by this error in console:
30.01 14:20:04 [Server] Server thread/CRITICAL ErrorException: "mt_rand(): max(0) is smaller than min(1)" (EXCEPTION) in "OreGen.phar/src/Xenophilicy/OreGen/OreGen" at line 61

**Comment by Xenophilicy** [comment]
Hello @timothytay, 

I am very sorry you are experiencing this issue. Thank you for the error, that helps narrow the issue down a lot. 

In order to confirm your issue, may I ask if you are running the latest update yet (**v1.0.3**)? If so, would you mind refreshing your data for OreGen by deleting the config.yml (_possibly settings.yml_) inside your plugin data folder? This will create a new config file with the updated inputs. *Note: If you are using a release from Poggit, as of 2/1/19 9:20 CST, the release for the new version is not available, as it has not been approved yet (hopefully soon they will wake up).* You can however download the latest [**here**](https://github.com/Xenophilicy/OreGen/archive/master.zip) at GitHub from the master file. Thanks for your patience.

Please let me know if this resolves your issue. Thanks!

**Comment by Xenophilicy** [comment]
Issue was resolved in an update made to the plugin. Please download the latest version to continue to use the plugin with full functionality. Thanks!
